use std::env;
use std::fs;
use std::path::PathBuf;

// protobuf-codegen names its output after the input file (`ttrpc.rs`),
// while prost-build names it after the protobuf package (`grpc.rs`).
// The schema keeps its original `package grpc`; the difference is
// absorbed here by the generated module glue instead of changing the
// protocol identity.
#[cfg(not(feature = "prost"))]
const GENERATED_MOD: &str = "ttrpc";
#[cfg(feature = "prost")]
const GENERATED_MOD: &str = "grpc";

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let path: PathBuf = [out_dir.clone(), "mod.rs".to_string()].iter().collect();
    fs::write(path, format!("pub mod {GENERATED_MOD};")).unwrap();

    generate_ttrpc(&out_dir);
}

#[cfg(not(feature = "prost"))]
fn generate_ttrpc(out_dir: &str) {
    let customize = protobuf_codegen::Customize::default()
        .gen_mod_rs(false)
        .generate_accessors(true);

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(out_dir)
        .inputs(["src/ttrpc.proto"])
        .include("src")
        .customize(customize)
        .run()
        .expect("Codegen failed.");
}

#[cfg(feature = "prost")]
fn generate_ttrpc(out_dir: &str) {
    let mut config = prost_build::Config::new();
    config
        .out_dir(out_dir)
        .compile_well_known_types()
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile_protos(&["src/ttrpc.proto"], &["src"])
        .expect("Codegen failed");

    // prost generates the `Code` enum variants in PascalCase (e.g. `Ok`,
    // `Cancelled`), while the rest of this crate and the rustprotobuf
    // backend reference the original SCREAMING_SNAKE_CASE names (e.g.
    // `OK`, `CANCELLED`). Add compatibility constants instead of
    // rewriting the generated source text.
    let generated_path = format!("{out_dir}/{GENERATED_MOD}.rs");
    let mut content = fs::read_to_string(&generated_path).expect("Failed to read generated code");
    // The proto doc comments use indented list items that newer toolchains
    // flag via clippy::doc_overindented_list_items, and prost does not emit
    // documentation for every generated item. Silence both lints for the
    // generated module.
    content = format!("#![allow(clippy::doc_overindented_list_items, missing_docs)]\n{content}");
    content.push_str(CODE_COMPAT_CONSTANTS);
    fs::write(&generated_path, content).expect("Failed to write generated code");
}

/// Compatibility constants mapping the historical SCREAMING_SNAKE_CASE
/// `Code` variant names onto the PascalCase variants generated by prost.
#[cfg(feature = "prost")]
const CODE_COMPAT_CONSTANTS: &str = r#"
impl Code {
    pub const OK: Self = Self::Ok;
    pub const CANCELLED: Self = Self::Cancelled;
    pub const UNKNOWN: Self = Self::Unknown;
    pub const INVALID_ARGUMENT: Self = Self::InvalidArgument;
    pub const DEADLINE_EXCEEDED: Self = Self::DeadlineExceeded;
    pub const NOT_FOUND: Self = Self::NotFound;
    pub const ALREADY_EXISTS: Self = Self::AlreadyExists;
    pub const PERMISSION_DENIED: Self = Self::PermissionDenied;
    pub const UNAUTHENTICATED: Self = Self::Unauthenticated;
    pub const RESOURCE_EXHAUSTED: Self = Self::ResourceExhausted;
    pub const FAILED_PRECONDITION: Self = Self::FailedPrecondition;
    pub const ABORTED: Self = Self::Aborted;
    pub const OUT_OF_RANGE: Self = Self::OutOfRange;
    pub const UNIMPLEMENTED: Self = Self::Unimplemented;
    pub const INTERNAL: Self = Self::Internal;
    pub const UNAVAILABLE: Self = Self::Unavailable;
    pub const DATA_LOSS: Self = Self::DataLoss;
}
"#;
